### ISSUE TITLE
Ignoring Specific Users using their IDs?

### ISSUE THREAD

**Issue by p00boy** [markokajzer/discord-soundbot#11]

**Comment by markokajzer** [comment]
This is a good idea. Will try to implement soon.

**Comment by markokajzer** [comment]
What do you think is more reasonable: Block users from using any command at all, or block them from playing sounds only?

**Comment by p00boy** [comment]
Sorry for the late reply - completely forgot about this.

I think ignoring the user completely would be better, since there's other commands that can be used to mess with the bot which would partly defeat the purpose of putting users on the blacklist in the first place.

**Comment by markokajzer** [comment]
Happy to announce that this funcitonality is implemented as of [now](https://github.com/markokajzer/discord-soundbot/releases/tag/v0.9.0)!
