### ISSUE TITLE
Bot doesn't join voice channel

### ISSUE THREAD

**Issue by SodaMazing** [markokajzer/discord-soundbot#12]
I added a sound in the bot, a very low-size sound of just a few KBs, i typed the command to play it, but the bot doesn't join the channel and play it. I tried different file types but nothing worked.
How do i fix this?

**Comment by mahmedov** [comment]
Can you post the terminal log?

**Comment by markokajzer** [comment]
@mahmedov Thanks for helping!

@SodaMazing Did you correctly install the deps without errors? Is there any console output? Do the other commands work fine? Which node version are you using?

**Comment by SodaMazing** [comment]
Nevermind, i have fixed it.
The problem was that i forgot to properly install FFMPEG.
