### ISSUE TITLE
Unable to add sounds

### ISSUE THREAD

**Issue by abecx** [markokajzer/discord-soundbot#122]
When attempting to add sounds I get the following error.  It does not matter the video from youtube or if you specify a duration or not.  I am using the latest docker image

markokajzer/discord-soundbot       latest        9e12cac38f14   4 weeks ago     436MB

(node:29) UnhandledPromiseRejectionWarning: Error: Status code: 404
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:197:27)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by markokajzer** [comment]
Hey, thanks for the report!

I just want to let you know that this was already discussed on the support server and I am aware of the issue. My hunch is that the library used to download stuff from youtube is out of date and the bot is a few versions behind. I was not able to access my PC these past days but my hope is to fix this very very soon.

I also want to setup dependabot for this particular dependency to stay up to date automatically.

Cheers :peace:

**Comment by markokajzer** [comment]
Fixed in e3cf11a8ade43e08509622298e969fb0b25cfc68
