### ISSUE TITLE
Python/Opus build error

### ISSUE THREAD

**Issue by Flatfire** [markokajzer/discord-soundbot#14]
![image](https://user-images.githubusercontent.com/9116816/29194064-f5e6522e-7df5-11e7-8e1c-c1c29b1f851a.png)

I'm working with Node 7.10. Opus seems to have issues building and it seems to have issues locating Python's executable despite looking in the correct directory.

**Comment by markokajzer** [comment]
Sorry for the long silence!

Unfortunately, you are using Windows so everything is a little bit harder here.
This is actually not an issue with this repo... However, there seems to be someone having similar issues. Refer to [here](https://github.com/Rantanen/node-opus/issues/30). Hope that helps!
