### ISSUE TITLE
Youtube download not working

### ISSUE THREAD

**Issue by MatWise** [markokajzer/discord-soundbot#155]
Seems like the Youtube download is broken again, (npm itself specifies that ytdl-core is out of date). Can you bump the dependencies?

**Comment by markokajzer** [comment]
Hey, what's up? Thanks so much for reaching out.

I was somewhat in a slump with this project between moving, getting a dog, adjusting to new jobs and roles, and didn't even have it running myself anymore.

BUT I installed the bot again recently and have it running myself, and I want to AT LEAST maintain it.

We really need to think about a way to do this semi-automatically, so maybe we can turn on Dependabot at least for `ytdl-core` and friends.

Again, thanks for reaching out. I hope to fix this soon 👍

**Comment by jhoffman1983** [comment]
Any updates coming? I love the bot and I've been able to manually update the ytdl-core in the past manually to get it working again but it doesn't appear to be working after that anymore.

**Comment by markokajzer** [comment]
See https://github.com/markokajzer/discord-soundbot/issues/156#issuecomment-1479467315

**Comment by markokajzer** [comment]
The bot has been upgraded and downloading from YT should work again.

It could depend on the video, so if you find something sussy, join the Discord and let me know!
