### ISSUE TITLE
Error: OPUS_ENGINE_MISSING

### ISSUE THREAD

**Issue by del-duca** [markokajzer/discord-soundbot#17]

**Comment by markokajzer** [comment]
Check if the node module 'node-opus' is installed. Otherwise, did you install ffmpeg?

**Comment by BrunoMarley69** [comment]
Hello, I'm having the same problem if you can help me?
I have the ffmpeg.
https://prnt.sc/gqg8pm
https://prnt.sc/gqg8xo

I hope you respond and a good day.

**Comment by markokajzer** [comment]
Is one of the modules "node-opus" (recommended) or "opusscript" installed?
What's your node version?

**Comment by del-duca** [comment]
my problem with this was I used a snapshot on Digital Ocean that was pre-built with Node JS, which was missing opus, I just started over with a new droplet, installed Node JS and ffmpeg and everything worked without a problem

**Comment by markokajzer** [comment]
Glad to hear!

**Comment by BrunoMarley69** [comment]
I do not know what's installed.
My version of the node is - 8.6.0

**Comment by markokajzer** [comment]
It would be good if you could find out what is and what isn't installed! 😄
Is `node-opus` in your `node_modules` folder?
I see you are using Windows. Is it 32 Bit (x86) or 64 Bit (x64)? node-opus only supports x64.

**Comment by BrunoMarley69** [comment]
I have now checked the folder node_models and have no node-opus.
And my version is 64 Bit (x64).

**Comment by markokajzer** [comment]
As you can see [here](https://github.com/markokajzer/discord-soundbot/blob/master/package.json#L10) node-opus is a dependency of this project. It is used for voice functionality [discord.js](https://github.com/hydrabolt/discord.js/#audio-engines). It should be autoamtically installed though when you do `npm install`, so maybe there was an error when installing the dependencies of discord-soundbot. Try installing them again.

**Comment by BrunoMarley69** [comment]
I have refined everything again and it did not work, I will not insist anymore, I apologize and thank you for the time you have spent trying to help me.
