### ISSUE TITLE
Some sounds won't play

### ISSUE THREAD

**Issue by Penetrosity** [markokajzer/discord-soundbot#2]
I have quite a few sounds on the bot at this point (182)

After updating it it seems some sounds just refuse to play while others will without a problem.
They all have the same Rights, the sizes differ, just some will not play.
No error, he just joins the voice channel and never plays the sound.

Some that will not work:
!vine_bruh
!VGW

Some that will work:
!shia_katana
!mk_fatality

It actually crashed after trying VGW, so here's that npm-debug.log
If giving you the sounds will help let me know and I'll try to upload them.

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.9
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dicord_soundbot@0.3.0~prestart: dicord_soundbot@0.3.0
6 silly lifecycle dicord_soundbot@0.3.0~prestart: no script for prestart, continuing
7 info lifecycle dicord_soundbot@0.3.0~start: dicord_soundbot@0.3.0
8 verbose lifecycle dicord_soundbot@0.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle dicord_soundbot@0.3.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/shazboi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/bin:/root/go/bin
10 verbose lifecycle dicord_soundbot@0.3.0~start: CWD: /root/shazboi
11 silly lifecycle dicord_soundbot@0.3.0~start: Args: [ '-c', 'node bot.js' ]
12 silly lifecycle dicord_soundbot@0.3.0~start: Returned: code: 1  signal: null
13 info lifecycle dicord_soundbot@0.3.0~start: Failed to exec start script
14 verbose stack Error: dicord_soundbot@0.3.0 start: `node bot.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid dicord_soundbot@0.3.0
16 verbose cwd /root/shazboi
17 error Linux 2.6.32-042stab116.2
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.5.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error dicord_soundbot@0.3.0 start: `node bot.js`
22 error Exit status 1
23 error Failed at the dicord_soundbot@0.3.0 start script 'node bot.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dicord_soundbot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node bot.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dicord_soundbot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dicord_soundbot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by markokajzer** [comment]
Yeah, sure. Could you upload them somewhere or just send them to my Github email?

**Comment by Penetrosity** [comment]
https://drive.google.com/file/d/0B8SdQ28LEu0EZDlkbnNkbGQ3dmM/view?usp=sharing
https://drive.google.com/file/d/0B8SdQ28LEu0EM1BGNFY1VmhhQzQ/view?usp=sharing
https://drive.google.com/file/d/0B8SdQ28LEu0EeU1xWjFHa3A2Snc/view?usp=sharing
https://drive.google.com/file/d/0B8SdQ28LEu0EOEpyenRWUmtmQlU/view?usp=sharing

**Comment by markokajzer** [comment]
You haven't made the files accessible by others! :-D

**Comment by Penetrosity** [comment]
Sorry, should work now.

**Comment by markokajzer** [comment]
So, yeah... As I already said there is a bug in [discord.js](https://github.com/hydrabolt/discord.js/issues/729) with sounds that are ~1 second in size. `vine_bruh` 71ms is and `VGW` is 1s7ms long, so I guess they are affected by this bug. I will test this on my machine in the next couple of days but I am quite convinced that this is due to the same bug mentioned in the linked issue.

I am terribly sorry, but there is nothing I can do at this point. I am waiting for them to fix this, as I am affected by the same issue as well as describe above.

I will update this issue when they've fixed it and my sounds work again!

**Comment by Penetrosity** [comment]
No problem, thanks for the responses!

**Comment by markokajzer** [comment]
I created a [branch](https://github.com/markokajzer/discord-soundbot/tree/v8) that uses an older version of discord.js which surprisingly does not have the same problems. I hope you will continue using my bot! :)
