### ISSUE TITLE
Keep the Bot in Voice Channel

### ISSUE THREAD

**Issue by Sultansmooth** [markokajzer/discord-soundbot#20]
Is there a way to keep the bot in the voice channel? It leaves after playing the sound

**Comment by markokajzer** [comment]
As you can see [here](https://github.com/markokajzer/discord-soundbot#configuration), it is already possible! Use the new `stayInChannel` configuration option. 

Feel free to leave any feedback. Merry Christmas!

**Comment by Sultansmooth** [comment]
You're awesome man! Thanks! Merry christmas to you too!
