### ISSUE TITLE
[Feature] WAV-Support

### ISSUE THREAD

**Issue by Skyppid** [markokajzer/discord-soundbot#3]
I really like the bot. It's easier to use and works more reliable than other currently available sound bots, though the installation is a bit tricky. Nonetheless, what I am really missing here is support for WAV-files as well. I got mixed MP3 and WAV sounds and since both are well established standards for sounds and music, it would be really nice. Converting forth and back is a bit annoying (had to do so for another bot - only accepted WAV-files).

Great work, nonetheless!

**Comment by markokajzer** [comment]
Yes, you are probably right! I will try to make the accepted file extensions configurable via the settings, as well as the accepted file size.

**Comment by markokajzer** [comment]
This is implemented with as off now! Please try out the newest version and feel free to leave any comments and suggestions! :)
