### ISSUE TITLE
support range in !add from youtube

### ISSUE THREAD

**Issue by Shamus03** [markokajzer/discord-soundbot#35]
ytdl-core supports a [range option](https://github.com/fent/node-ytdl-core/blob/4af7ba06f690da15537943420bba2681567d73fe/lib/index.js#L96) to download only a portion of the video.  It would be nice to have this in the soundbot as well.

I think it should be enough to add a range option [here](https://github.com/markokajzer/discord-soundbot/blob/89d67d65a62b3705c36b9aeda9ac57c026e18e84/src/bot/commands/helpers/downloader/YoutubeDownloader.ts#L38).

What do you think about parsing start/end from the link's query parameters in `makeRequest` ?  This mirrors YouTube's current ability to add a range to an embed link (which already work for the add command).  Example: https://www.youtube.com/embed/ZWQ0591PAxM?start=120&end=240

Pending approval I could pick this up.  Doesn't seem like a large undertaking.

**Comment by Shamus03** [comment]
1. Looks like the range is a byte range meant for streaming, not a time range
2. There is a "begin" parameter that _is_ the time to start at, but it is considered unreliable/unstable

It would still be nice to have a range option though.

**Comment by markokajzer** [comment]
Hey @Shamus03! Thank you for the feature suggestion and for the research you already seem to have put in this. It would indeed be great to specify a range. 

It seems like this would be possible with ffmpeg as per [this](https://github.com/fent/node-ytdl-core/issues/345) post. I'll try to cook something up when I find the time.

Thank you for using the bot! Cheers.

**Comment by markokajzer** [comment]
Implemented on master! Please have a look and tell me if something is wrong.

**Comment by Shamus03** [comment]
Commit reference for future reference: a5d5c84fbfc94fbba0f121d8d1e55eda910090d1

Trying it out now!
