### ISSUE TITLE
Verbose Stack Error

### ISSUE THREAD

**Issue by Quartos** [markokajzer/discord-soundbot#36]
Hi,
after some days of normal operation, it seems that the bot just randomly crashed. The npm log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-soundbot@1.5.0-dev~prestart: discord-soundbot@1.5.0-dev
6 info lifecycle discord-soundbot@1.5.0-dev~start: discord-soundbot@1.5.0-dev
7 verbose lifecycle discord-soundbot@1.5.0-dev~start: unsafe-perm in lifecycle true
8 verbose lifecycle discord-soundbot@1.5.0-dev~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/matthias/discord-soundbot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle discord-soundbot@1.5.0-dev~start: CWD: /home/matthias/discord-soundbot
10 silly lifecycle discord-soundbot@1.5.0-dev~start: Args: [ '-c', 'npm run build && npm run serve' ]
11 silly lifecycle discord-soundbot@1.5.0-dev~start: Returned: code: 1  signal: null
12 info lifecycle discord-soundbot@1.5.0-dev~start: Failed to exec start script
13 verbose stack Error: discord-soundbot@1.5.0-dev start: `npm run build && npm run serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid discord-soundbot@1.5.0-dev
15 verbose cwd /home/matthias/discord-soundbot
16 verbose Linux 3.16.0-4-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v9.3.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error discord-soundbot@1.5.0-dev start: `npm run build && npm run serve`
22 error Exit status 1
23 error Failed at the discord-soundbot@1.5.0-dev start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Is there any fault on my side?

**Comment by markokajzer** [comment]
Hey dude,

sorry for the super late answer. For some reasons GitHub email notifications land immediately in my trash...

Unfortunately, the error messages does not really help... Are you on Windows by chance? There are always some odd errors with it. What is your node version? Try installing node v8 and delete / re-install `node_modules`.

Hope this will help. If you encounter any more problems feel free to add something here, or join the Discord where I could try to help you in more detail.

**Comment by Quartos** [comment]
Hey,
don't worry about it! The bot runs on Debian 8, node version should be the latest you can get by installing the corresponding package (I basically just followed your install instructions for [Unix](https://github.com/markokajzer/discord-soundbot/wiki/Unix)). 

I might've found the cause by now. The stayInChannel attribute was set to true and since the people on my server (myself included) did not care about commanding the bot to leave, it basically stayed in the same channel until the next crash. The timings of the crashes first looked random to us, but after a while it more and more seemed like they always occur after the bot was idle for some time and inside one of our channels. Long story short: No more crashes so far after setting stayInChannel to false (that was around 3 days ago). Before that they basically occured daily. I will of course observe the bot's further behaviour to see if any more crashes happen, but for now I suspect that the bot is unable to handle the automatic disconnect which is induced by discord if you're idle for too long. Can you look into it?

**Comment by Quartos** [comment]
Quick update: The fix above did not help, seems like this was just a random occurence. However, I meanwhile "solved" the problem by myself by just executing the npm start command in an infinite loop via a shell script. A bit hacky, but okay for my needs.

**Comment by markokajzer** [comment]
Strange indeed. I will keep an eye on that, thank you very much for your report! My bot crashed as well a couple of days ago. Unfortunately, I cannot access it since it is on a Raspberry Pi at my parents' place and I do not know the IP :D

I will see if it was the same issue when I can access it again.

**Comment by markokajzer** [comment]
I will close this issue due to inactivity. If you have anything else, feel free to open another PR, or talk to me on Discord.
