### ISSUE TITLE
ref package error

### ISSUE THREAD

**Issue by Indiana8000** [markokajzer/discord-soundbot#4]
On Ubuntu 16.10 it looks like some dependencies are unmet.

[npm-debug.log.txt](https://github.com/markokajzer/discord-soundbot/files/850776/npm-debug.log.txt)

> ref@1.3.4 install /tmp/asd-root/home/andy/discord-soundbot/node_modules/ref
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-39-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/asd-root/home/andy/discord-soundbot/node_modules/ref
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN discord.js@11.0.0 requires a peer of bufferutil@^2.0.0 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.2 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of sodium@^2.0.1 but none was installed.
npm ERR! Linux 4.8.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/asd-root/home/andy/discord-soundbot/npm-debug.log

**Comment by markokajzer** [comment]
Sorry for the late answer!

As stated [here](https://github.com/markokajzer/discord-soundbot#requirements) you have to use Node v6.0.0 or higher. Your logs reveal you are using 
```
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
```

Try upgrading and report results please!

**Comment by Indiana8000** [comment]
Thanks, didn't thought that the latest Ubuntu run a so old nodejs version. With v6.10.0 LTS it is working.

**Comment by markokajzer** [comment]
The packages are (optional)[https://github.com/hydrabolt/discord.js#optional-packages] packages from the discord.js library. Find more information on the linked page! 😁
