### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by MarcoReckless** [markokajzer/discord-soundbot#44]
I don't know what causes this, but it happens every once in a while.

```
(node:24141) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at item.request.gen.end (/root/Desktop/discord-soundbot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
    at then (/root/Desktop/discord-soundbot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:24141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by markokajzer** [comment]
Hey, thanks for the report! As we discussed on Discord, this might have something to do with your folks manually deleting your bot's messages.

How to consistently reproduce:

1. Trigger sound
2. Manually delete message
3. Bot tries to delete message
4. We get the error

There is a `.deletable` attribute on `Message`, but it does not seem to help in this case. I have another idea how to mitigate this issue and I will report back as soon as I can test it out.

**Comment by markokajzer** [comment]
Unfortunately, there is no easy solution to this, as we cannot actually get if a message was deleted or not.

I prepared a fix that should work in most cases. Please try it out and report back if something is wrong. Either way, if you have `deleteMessages: true;` you can leave deletion to the bot.
