### ISSUE TITLE
Add non-youtube sounds

### ISSUE THREAD

**Issue by johnmosesman** [markokajzer/discord-soundbot#47]
Is it possible to add sounds that are not from Youtube URLs, but any arbitrary URL?

**Comment by markokajzer** [comment]
Hey man, thanks for trying out the bot. :wave:

Not yet, but I will definitely consider it, after seeing your suggestion on Discord as well!

You are thinking of urls like `example.com/example.mp3`, right?

**Comment by markokajzer** [comment]
I think I will close this for now. I feel like it is easiest to download a given sound and upload it to the bot manually, I think. If more people would like to see this, I will re-open the issue.
