### ISSUE TITLE
User entrance sounds are lost after the bot is restarted

### ISSUE THREAD

**Issue by z1g** [markokajzer/discord-soundbot#55]
Hello and thank you for the time you have spent on this project.  Myself and my users are enjoying it very much.  I am running this with Ubuntu 18.04 and Node 8.10.  For me, users can set entrance sounds successfully via the command and the sounds play properly, however if the bot is restarted it will no longer play the entrance sounds until the users set them back up again.

**Comment by markokajzer** [comment]
Hey! Thanks for using the bot and the nice words. :)

I was just approached on the Discord about this issue as well. I don't use the entrance sounds myself so I didn't realize that they don't work... Pretty unfortunate! I have an idea what might be wrong, and will try to look into it this weekend.

Until then, it seems like they are persisted when you manually save them in `db.json`, so you can try to do that for now.

**Comment by Jufoli** [comment]
> Until then, it seems like they are persisted when you manually save them in db.json, so you can try to do that for now.
What format has the value of "entrance" and "exit"? What kinda Objects do they need?

**Comment by markokajzer** [comment]
That would be

```json
"entrances": {
  "userId": "soundName",
  "userId2": "soundName"
}
```

**Comment by ziotron** [comment]
Spoke with Marko just a moment ago. He's going to tackle it this weekend. 

SOLID bot might I add.

**Comment by z1g** [comment]
> 
> 
> That would be
> 
> ```json
> "entrances": {
>   "userId": "soundName",
>   "userId2": "soundName"
> }
> ```

Thanks, adding them manually worked like a charm.

**Comment by markokajzer** [comment]
Should be fixed in master. Could you pull in the latest changes and try again? Please let me know if everything works as expected.
