### ISSUE TITLE
Illegal Instruction: 4

### ISSUE THREAD

**Issue by ili-codes** [markokajzer/discord-soundbot#6]
I'm trying to use this on Mac OS X Lion 10.7.5 on an old Mac Mini I've got lying around, but I keep getting the error `Illegal instruction: 4` when I'm running `node bot.js`. Why does this happen and how can I fix it?

**Comment by markokajzer** [comment]
Node version?

**Comment by ili-codes** [comment]
`npm install`'d.

**Comment by markokajzer** [comment]
I would guess it's something similar to [this](https://raspberrypi.stackexchange.com/a/30068) as you are using quite an old version of Mac OS where V8 did not exist yet. Try to run `node --v8-options` and see if you can get some information out of it.

**Comment by ili-codes** [comment]
I'm away from the machine at the moment, but I'll try when I can. Thanks!

**Comment by ili-codes** [comment]
`SSE3=1 SSE4_1=0 SAHF=1 AVX=0 FMA3=0 BMI1=0 BMI2=0 LZCNT=0 POPCNT=0 ATOM=0` is what I'm getting.

**Comment by markokajzer** [comment]
I really cannot help you here. This is a problem that has nothing to do with this project, but with the CPU in the Mac Mini. Something is wrong with your build setup. `Illegal Instruction` means that you have some binary which is trying to execute an invalid CPU instruction.

That could be for various reasons. For example, but not limited to:
+ Your compilation generated broken binary for your platform
+ Your system has bad binary from different architecture which it is trying to run
+ Your source code of Node.js has a bug (for example, integer overflow) which causes memory corruption and leads to Illegal Instruction

Start debugging by installing the newest node version (v7.10.0) and try running again.
Try upgrading to the newest Mac OS version and re-install node.
