### ISSUE TITLE
Bot not playing sound

### ISSUE THREAD

**Issue by kubsar** [markokajzer/discord-soundbot#7]
The bot is joining the channel and leaves it immediately without playing the sound. Tried multiple file formats, sizes. Tried to debug myself, but doesn't throw any errors. Help would be appreciated.

**Comment by markokajzer** [comment]
Did you install FFmpeg? This is needed because of the voice functionality.

**Comment by kubsar** [comment]
FFmpeg is installed, it doesn't throw Any errors when playing a sound. The file paths are correct as well. Using Node version 7.10.0

**Comment by kubsar** [comment]
I'm on Ubuntu 16.10

**Comment by kubsar** [comment]
Tried everything you suggested me to do, still the same behavior. Bot joins and leaves immediately. Tried to run with the bare minimums, no errors thrown. Every dependency needed is installed, still no luck. Bot works fine for others I guess, don't know what's wrong.

**Comment by markokajzer** [comment]
Closed due to no updates.
