### ISSUE TITLE
Set game status using !config to string. Request.

### ISSUE THREAD

**Issue by jusplainmike** [markokajzer/discord-soundbot#76]
I've tried using " and ' around my game status but it only updates the word. Is there any way to update the config game status without restarting the server? Example when I type !config game "here is my update" it only changes to "here .

**Comment by markokajzer** [comment]
Hey! Sorry for the late answer. :(

Thank you so much for the bug report! And you are right, I know what's wrong, and I'll fix it in the coming days :)

For now change activity via the config file + restart the bot.

**Comment by jusplainmike** [comment]
No worries. I am using a custom mqtt client with discordpy and your bot for
audio.

**Comment by markokajzer** [comment]
Should be fixed in c20c2633d8b57f318ca1b485bc8e55587ca502e3.
