### ISSUE TITLE
Disconnect Loop

### ISSUE THREAD

**Issue by jcr1985** [markokajzer/discord-soundbot#8]
The bot works great at all but after a time idling it starts to disconnect/reconnect every couple of seconds. It does not take long until i get an email from discord telling me they reset the token because of potential abuse of the bot because it reconnected over 1000 times.

Here are some errors from the console:
`
Use the following URL to let the bot join your server!
https://discordapp.com/oauth2/authorize?client_id=303184336902029312&scope=bot
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/discord/discord-soundbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:256:26)
    at connectTimeout.client.setTimeout (/home/discord/discord-soundbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:277:18)
    at Timeout.setTimeout (/home/discord/discord-soundbot/node_modules/discord.js/src/client/Client.js:420:7)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
discord@jcrnet:~/discord-soundbot$ node bot.js 
Use the following URL to let the bot join your server!
https://discordapp.com/oauth2/authorize?client_id=303184336902029312&scope=bot
(node:27661) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 404 Not Found
`
Any ideas?

TIA,
jcr

**Comment by markokajzer** [comment]
OS? Node.js version? FFmpeg installed? Is the bot able to play sounds at first or not at all?

**Comment by jcr1985** [comment]
Ubuntu 16.04.2 LTS

nodejs -v
v6.10.2

ffmpeg version 2.8.11-0ubuntu0.16.04.1

Bot is running great most of the time and playing sounds very well.

**Comment by markokajzer** [comment]
Strange... I run the same setup except node v6.10.3.
Anyway, as you can see from the logs it's not actually a problem with this repo but with discord.js. Maybe you can ask over there?

There is are two issues with similar errors:  [This one](https://github.com/hydrabolt/discord.js/issues/1296) with no real conclusion and [that one](https://github.com/hydrabolt/discord.js/issues/696#issuecomment-246746851) that points to bad network connection as a possible error. This would be also my next guess, so maybe the device you are running the bot on just has a very bad connection every once in a while. Firewall issues?

**Comment by jcr1985** [comment]
I will give it a try.

Network Connection should not be a problem. It is a very good VPS with a stable connection running game servers and stuff on it without problems.

Anyway thanks for your feedback. Will post it here if i find a solution.
