### ISSUE TITLE
Crash on raspberry pi 3b+

### ISSUE THREAD

**Issue by torring97** [markokajzer/discord-soundbot#84]
Hi, 
first thanks for the bot; it is very useful and funny, me and my friends use evryday.
I've installed  the bot on my raspberry pi 3b+ with the last raspbian and it continue to crash with the same log (attached it as txt [Log bot discord.txt](https://github.com/markokajzer/discord-soundbot/files/4669960/Log.bot.discord.txt))

could you take a quick look? if it's something difficult to fix no problem

**Comment by markokajzer** [comment]
Talking to you on Support Discord. Will update answer when we find a solution.
