### ISSUE TITLE
[Feature Request] Remove commands sent to unmonitored channels

### ISSUE THREAD

**Issue by prenetic** [markokajzer/discord-soundbot#89]
Building on issue #54's proposed channel monitoring functionality, it makes sense for the bot to also remove errant commands sent to an unmonitored channel.

In this scenario, if any channels are specified for monitoring on a given a server, commands sent to the bot in any unmonitored channel on that server should be automatically removed in conjunction with the instructions sent to the user via DM from issue #54.

If no channels are specified for monitoring on a given server, follow current behavior (monitor/allow all commands in any channel).

**Comment by markokajzer** [comment]
Oh man, I am so sorry... I completely misunderstood your initial request because I misread it. :(

I will close this issue and keep the related discussionin the other issue.

**Comment by prenetic** [comment]
No worries!
